### ISSUE TITLE
Clarification on remote execution path

### ISSUE THREAD

**Issue by Meowzz95** [Meowzz95/mi_nus_cluster_gpu_status#3]
@lv2020 Hi, thanks for your PR on multi-thread support.
I just checked the code and found that you've added `os.getcwd()` in the remote execution path. May I know how does it work? From what I know the SoC server default at home dir which is the place we put the slave script at. So a direct call to `python slave_script` should work. On the other hand, if our local execution path does not exist(most probably not) on the server, won't the remote call fail?
Eg:
My local execution path: /home/myname/myproject/folder/main.py
then the remote call on the server become:
`python3 /home/myname/myproject/folder/mi_gpu_slave_script.py`
This path should not exist on the server right?

I'm referring to this line.
https://github.com/Meowzz95/mi_nus_cluster_gpu_status/blob/7b7b8edad3e3dc7ce6b2ec945af86f00243a3cdb/src/mi_nus_soc_gpu_status_reader.py#L112

Appreciate if you can help on this.

**Comment by YipingRuan** [comment]
It will only work when the scripts (both) are put at the soc node and run from there.

**Comment by lv2020** [comment]
Because I don't put the script at home dir, I just git clone the whole repo. So it needs to set the local execution path. Or the status list would return empty. The remote call would fail if we execute the script in a different path. Maybe there is a better way to solve this problem.

**Comment by Meowzz95** [comment]
@YipingRuan @lv2020 
Looks like cloning the repo to one of the SoC server and run the script from there is a more common use case than the provided client-server approach. I will update the doc to use this approach instead. Thanks.

**Comment by Meowzz95** [comment]
PR: #4
